### ISSUE TITLE
can not preview \bm using the Math Preview Pannel

### ISSUE THREAD

**Issue by Burt1018** [XuehaiPan/LaTeX-Templates#1]
when use the Math Preview Pannel, I can not preview a bold symbol but a red \bm x

**Comment by XuehaiPan** [comment]
@Burt1018 LaTeX/TeX is a compile-based language. You need always compile the document to get the final result. The preview panel of LaTeX-Workshop is based on [MathJax](https://www.mathjax.org/), it only implements some of the basic math commands (not all). You can find the list of implemented commands at [Supported TeX/LaTeX commands](https://docs.mathjax.org/en/latest/input/tex/macros/index.html). If you want to preview the equations without compiling them, use `\boldsymbol` or `\mathbf` instead.
